### ISSUE TITLE
Import Tournaments from Cryodex and Tabletop.to

### ISSUE THREAD

**Issue by AlexRaubach** [AlexRaubach/ListFortress#1]
Need to build a tournament and participants from the incoming json.

**Comment by AlexRaubach** [comment]
Tabletop.to imports are on hold until I get a license from the site manager[ because of the site's TOS (2.a.ii)](https://tabletop.to/TOS)

**Comment by AlexRaubach** [comment]
TTT is now supported

**Comment by AlexRaubach** [comment]
You can now paste in cryodex / TTT json

**Comment by PiecePaperCode** [comment]
cryodex has not received an update since 2y and ttt went offline. there is a need for an xws tournament data format that works across all apps.
