### ISSUE TITLE
Pagination missing tournaments

### ISSUE THREAD

**Issue by calumbrown** [AlexRaubach/ListFortress#12]
Certain tournaments don't appear under the paginated tournament listing. At the time of writing tournaments with ids 186, 219, 235 and 236 don't seem to be listed, but are existing events:
e.g. https://listfortress.com/tournaments/235

There are also some tournaments that are listed on more than one page (e.g. 230, which appears on page 1 and 2 at the time of writing).

**Comment by AlexRaubach** [comment]
That's weird. Thanks for making an issue and I'll look into it

**Comment by AlexRaubach** [comment]
Yup, some tournaments are being shown twice and some not at all. Right now I'm sorting only by date. If I sort by date and then by id, the db won't have any ties in the tournament ordering.

**Comment by AlexRaubach** [comment]
The additional ordering seems to have resolved the issue
