### ISSUE TITLE
Search tournaments by any column in tournament table

### ISSUE THREAD

**Issue by nateyj** [AlexRaubach/ListFortress#29]
Hello. Love List Fortress and not sure where to submit this feature request.

It would be awesome to be able to search the tournaments by any of the columns in the table (i.e., name, location, date, format, type, etc.). Unless I know the person who submitted the tournament and can get the URL from them, I often can't find tournaments I'm interested in seeing, especially tournaments I didn't participate in. I end up manually paging and visually checking tournament dates to find them.

Thank you again for all of the hard work that's put into this! It's wonderful.

**Comment by AlexRaubach** [comment]
Just rolled this out in #30, it's still missing location/state (I'd prefer a better way of searching than just using sql where like type query that I used for name) and I still want to add the option to sort by different columns.
