### ISSUE TITLE
Duplicate tournament created for Sith Taker Open

### ISSUE THREAD

**Issue by chrisalleng** [AlexRaubach/ListFortress#46]
Both of these:
https://listfortress.com/tournaments/2854
https://listfortress.com/tournaments/2855

were created for the Sith Taker Open by mistake. Looks like 2855 is populated and completed, and 2854 should be safely deleted.

**Comment by AlexRaubach** [comment]
Done. If you create an account on listfortress by signing in with your Vassal League Slack account on the [league page](https://listfortress.com/league) and then send me the id via pm or reddit message or email, I'll make your account an admin so you can just delete them directly.
