### ISSUE TITLE
Lists cleared while updating player stats

### ISSUE THREAD

**Issue by chrisalleng** [AlexRaubach/ListFortress#6]
When you edit a participants data and leave the list blank while doing so, the list that was stored for that participant is cleared if it existed.

This means any time you touch a participant, you need the original squad URL to paste in when updating scores, cut rank, etc, or the participant list is deleted.

Would be nice for the default behavior to be no change to the stored list when nothing is entered into the participant squad box when one is already saved for that participant.

**Comment by AlexRaubach** [comment]
Adding an XWS field to the Participant update form should have resolved this.
