### ISSUE TITLE
Imports from Longshanks

### ISSUE THREAD

**Issue by sebald** [AlexRaubach/ListFortress#66]
Hey there!

I am the dev of https://pattern-analyzer-xwing.vercel.app/ 👋

The apps crawls longshanks for data and I think I have all it needs to make it possible to create an export for listfortress.

I tested it with this tournament: https://listfortress.com/tournaments/3506 (can you delete it the tournament is not over yet ...ehem) I fixed the "squad error". Will no longer be `null` but rather an empty string if there is no list.

Funwok also tested it but I guess sending lists as XWS does't work? :-/ Can you delete this tournament too? https://listfortress.com/tournaments/3505 Sorry for the trouble! I switched to sending them as strings which works as seen on the 3506 tournament.

This feature is not fully released yet, but you can take a look at the preview if you like: https://pattern-analyzer-git-list-fortress-sebald.vercel.app/

So, if you think this looks alright, I would release it so we hopefully can have more data and tournaments from events that are hosted on longshanks 😃

**Comment by AlexRaubach** [comment]
This is amazing, thanks! @chrisalleng and I had been talking about adding the ability to scrape data from longshanks into listfortress but this is much better than what I was going to eventually hack together.

One minor piece of feedback is that I did like how rollbetter had a link directly to [listfortress's new tournaments page](https://listfortress.com/tournaments/new) in their export modal which I thought was convenient for users but other than that, thanks 🥳

**Comment by chrisalleng** [comment]
@sebald awesome, thanks so much!

**Comment by sebald** [comment]
@AlexRaubach @chrisalleng thanks, glad you like it.

The framework I am using to build the site is still in beta did the whole thing as part of a technical evaluation at work). They didn't add/migrate the possibility to have an API yet. As soon as the have, I'll add this 😄
