### ISSUE TITLE
Addition of 2.0 Legacy specific format

### ISSUE THREAD

**Issue by SogeMoge** [AlexRaubach/ListFortress#68]
Hello from [X2PO team](https://x2po.org/). Since 2.0 Legacy movement is growing stronger and more competitive tournaments incoming, we were wondering if it is possible to add new game format for entering tournament results and filtering only Legacy data?

Legacy has renamed **Extended** format to **Standard** for better compatibility between 2.0 and 2.5.
New format could be "**2.0 Legacy Standard**".

**Comment by AlexRaubach** [comment]
Hey, thanks for reaching out. New formats are definitely possible, I just have a couple questions about what you're looking for and if maybe just renaming the existing formats would be a better fit?  

Right now, I have seven different formats, two of which are deprecated i.e. tournaments exist with that format so you can filter on them but you can't make new tournaments in that format.

name| deprecated 
--|--
2.5 Standard | false
2.5 Extended | false
2.0 Hyperspace |  false
2.0 Extended | false
Other |  false
Second Edition | true
Custom | true

One option is to just change the name of 2.0 extended to something like 2.0 Standard/Extended. You can just include a date range on whatever filtering you're trying to do if you only want legacy tournament data.

Alternatively, I could deprecate 2.0 Hyperspace and 2.0 Extended and replace them with 2.0 Legacy Hyperspace and 2.0 Legacy Standard? Looking at [list fortress](https://listfortress.com/tournaments?min_participants=&max_participants=&format_id=1&tournament_type_id=&country=&name_search=&played_after=&played_before=&sort_order=), the only 2.0 events from the past year seem to be legacy events, so this shouldn't cause any problems. You could even edit the existing legacy events to use the new format if you wanted to. 

Let me know what you think, I'm fine with either solution.

**Comment by SogeMoge** [comment]
_Firs of all thank you for great thorough response and cooperation._ 
Am I getting it right that deprecated format will be still present for retrospective data but you cant use it for new data entry? We still use those for data analyze. If so we've decided that the second option is more desirable.
Personally I think it would be nice to preserve FFG era in deprecated formats, at least as a tribute to great times.

lets deprecate following formats:
- 2.0 Hyperspace
- 2.0 Extended
There is not enough people willing to run vanilla tournaments anyway, close to zero.

Add:
- 2.0 Legacy Standard
- 2.0 Legacy Wild Space

Wild Space will be the new mode incorporating Standard loadouts, scenarios from 2.5 Battle Packs and custom objective play more suitable for 2.0 gameplay.

**Comment by AlexRaubach** [comment]
New formats are live, feel free to reopen if you encounter any issues with the changes
